### ISSUE TITLE
Login with google issue when you signed to chrome

### ISSUE THREAD

**Issue by zayass** [openid/AppAuth-Android#361] opened 2018-07-05 17:49 UTC
We found to related issues when trying google OAuth and chrome with signed in system account.

1. When you tap "Use another account" custom tabs opens chrome account settings instead of a login form. You can add system account on that page but this will not return you to custom tabs.

2. If you set login hint with `setLoginHint` first scenario starts automatically which is confusing even more. When you return to app only empty white screen appears in custom tabs.

**Comment by iainmcgin** [comment] 2018-07-05 23:09
Unfortunately these are known, long-standing issues with the way that Chrome's account management works on Android. See #172, #173 and #194. I was never able to get the Chrome team to fix these issues, and now I no longer work at Google so they have even less reason to listen to me 😭 

Closing this as an effective duplicate of the other issues. Sorry, there's very little we can do in this situation.

**Closed by iainmcgin** 2018-07-05 23:09 UTC

**Comment by zayass** [comment] 2018-07-06 01:14
Sorry for duplicates and thank you for links. Little bit tricky to find issues with such descriptions.
