### ISSUE TITLE
leaked ServiceConnection net.openid.appauth.BrowserHandler

### ISSUE THREAD

**Issue by nrgarach** [openid/AppAuth-Android#166] opened 2017-02-15 23:16 UTC
Activity has leaked ServiceConnection net.openid.appauth.BrowserHandler$1@4c6fd9c that was originally bound here
                                                                        android.app.ServiceConnectionLeaked: Activity com.....main.login.Oauth2AppLoginActivity has leaked ServiceConnection net.openid.appauth.BrowserHandler$1@4c6fd9c that was originally bound here
                                                                            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
                                                                            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
                                                                            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1412)
                                                                            at android.app.ContextImpl.bindService(ContextImpl.java:1395)
                                                                            at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
                                                                            at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:64)
                                                                            at net.openid.appauth.BrowserHandler.bindCustomTabsService(BrowserHandler.java:86)
                                                                            at net.openid.appauth.BrowserHandler.<init>(BrowserHandler.java:61)
                                                                            at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:98)

**Comment by iainmcgin** [comment] 2017-02-16 00:59
Duplicate of #91

**Closed by iainmcgin** 2017-02-16 00:59 UTC
