### ISSUE TITLE
Authorization response null

### ISSUE THREAD

**Issue by nrgarach** [openid/AppAuth-Android#148] opened 2017-01-18 23:22 UTC
Hi,

I am getting the error. "E/AppAuth: Response received for unknown request with state null". Can you please elaborate on how did you read "state" parameter?

I am using app-auth library on android. Sign up page takes me to form to enter details and once I am done, back of login should take me to my login page instead when I tap on back to login it does nothing and gives me above error. This works fine on browser but this issue exists only on android device.

**Comment by iainmcgin** [comment] 2017-01-20 06:34
Duplicate of #118.

**Closed by iainmcgin** 2017-01-20 06:34 UTC
