### ISSUE TITLE
After Azure sign in or Sign up it is not redirecting to the activity and not getting access Token or Any Logs in Logcat

### ISSUE THREAD

**Issue by VigneshKSI** [openid/AppAuth-Android#533] opened 2020-04-29 12:24 UTC
Currently I am using latest version API level version 29 and  it is redirecting to login page , but it was not redirecting to activity after sign in in web azure , What was the issue , Is there anything do we need to link like app linking or something , Please help me on this

I am sharing the screen as well , Please help me On this

After sign in Azure it was not redirecting to the activity.
![Screenshot_2020-04-29-17-48-39-548_com android chrome](https://user-images.githubusercontent.com/37724418/80595205-fbc94380-8a41-11ea-8b0b-2301c9e5b409.jpg)

And I need to these supporting platforms also

If I am trying in marshmallow or nougot it was redirecting to other url's from this page and saying that This site can't be reached pls see this screenshot also

![IMG-20200428-WA0021](https://user-images.githubusercontent.com/37724418/80595427-5c588080-8a42-11ea-8bc9-0816c3cc3fc3.jpg)

Thanks
Vignesh

**Comment by iainmcgin** [comment] 2020-05-27 18:15
Can you confirm that in your compiled app manifest a handler is registered for custom scheme `com.onmicrosoft.foodyhive.homefood`?

**Comment by VigneshKSI** [comment] 2020-05-28 03:26
Yes

**Comment by iainmcgin** [comment] 2020-05-28 18:16
Please share the section of your app manifest that registers the custom scheme handling, and also test the custom scheme handling using this adb command:

```
adb shell am start -W -a android.intent.action.VIEW \
  -c android.intent.category.DEFAULT  \
  -d com.onmicrosoft.foodyhive.homefood://oauth/redirect
```

The double-slash may be an issue, so also test:

```
adb shell am start -W -a android.intent.action.VIEW \
  -c android.intent.category.DEFAULT  \
  -d com.onmicrosoft.foodyhive.homefood:/oauth/redirect
```

If neither of those open your app, then there is some issue with the custom scheme registration.

**Comment by VigneshKSI** [comment] 2020-05-29 04:03
Okay let me test and will share the Android manifest register handling code as well

**Comment by VigneshKSI** [comment] 2020-06-03 07:43
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="https"
              android:host="com.onmicrosoft.foodyhive.homefood"
              android:path="//oauth/redirect"/>
    </intent-filter>
</activity>



This is my code in app android manifest ,Please check and let me know if any issues was there in this code 


And in app build.gradle file the code is like this

 manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.onmicrosoft.foodyhive.homefood'
            ]

**Comment by VigneshKSI** [comment] 2020-06-03 07:45
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="https"
              android:host="com.onmicrosoft.foodyhive.homefood"
              android:path="//oauth/redirect"/>
    </intent-filter>
</activity>

**Comment by VigneshKSI** [comment] 2020-06-11 04:01
Okay let me check with single slash and let you know

**Comment by thomasrliberto** [comment] 2020-06-23 18:22
@VigneshKSI did this work for you? I'm facing the same issue (although I'm using a Flutter wrapper for this library). My redirect URI has two slashes in it as well, which I put in a request to change but it will be a few days before it gets approved. Hopefully this solves my issue but I wanted to know if it worked for you. Redirection works for me on iOS, but not Android. I confirmed with the author of the Flutter wrapper that I'm using his plugin correctly, so I'm a little lost on what my issue is.

@iainmcgin would having double slashes actually cause it to not work? My redirect URI is " AppName://callback ". I'm going to change it to one slash (which will take a few days to get provisioned) but I'd appreciate some input now so I don't go and break something that is working correctly.

**Comment by iainmcgin** [comment] 2020-06-23 19:46
It may be possible to get it to work by using a different `<data>` specification on the intent filter. The issue is that `myscheme://a/b/c` will be interpreted as having a _host_ of `a` and path of `/b/c`.

Matching a custom scheme redirect URI without a slash, e.g. `myscheme:/a/b/c`, requires the following:

```xml
<data android:scheme="myscheme"
          android:path="/a/b/c"/>
```

Instead with a double slash, you would use something like:

```xml
<data android:scheme="myscheme"
          android:host="a"
          android:path="/b/c"/>
```

I have not tested capture of custom scheme redirects that use a host; my recommendation would definitely be to use a URI of form `myscheme:/path` rather than `myscheme://host/path`.

@VigneshKSI I just noticed looking back at the configuration you shared, and comparing to your screenshot, you appear to be mixing two very different ways of handling the redirect. In the screenshot of the failure in Chrome the redirect URI looks like `com.onmicrosoft.foodyhive.homefood://oauth/redirect` but you are attempting to capture an https scheme. This is incorrect, I think it should either look like

```xml
<!-- for a redirect like com.onmicrosoft.foodyhive.homefood://oauth/redirect -->
<data android:scheme="com.onmicrosoft.foodyhive.homefood"
          android:host="oauth"
          android:path="/redirect"/>
```

or

```xml
<!-- for a redirect like com.onmicrosoft.foodyhive.homefood:/oauth/redirect -->
<data android:scheme="com.onmicrosoft.foodyhive.homefood"
          android:path="/oauth/redirect"/>
```

**Comment by VigneshKSI** [comment] 2020-06-24 02:57
Thanks for you information let me change that and test it again and let you know

**Comment by VigneshKSI** [comment] 2020-06-24 05:43
I am facing same issue after changing the android manifest like mentioned also


<data android:scheme="com.onmicrosoft.foodyhive.homefood"
          android:host="oauth"
          android:path="/redirect"/>


For version 6 the result look like this screen 
![Screenshot_1592976671](https://user-images.githubusercontent.com/37724418/85504740-3eeeff80-b60a-11ea-838a-ddb1d9240414.png)



And For version abve 6 It means above marshmallow ,I am trying nothing is happened
![Screenshot_1592977041](https://user-images.githubusercontent.com/37724418/85505273-8fb32800-b60b-11ea-9792-cc59bb61d2f0.png)
![Screenshot_1592976671](https://user-images.githubusercontent.com/37724418/85505275-90e45500-b60b-11ea-8272-a965828eeb4b.png)



Can we change the redirect url to https in azure portal ?


Any idea ?

**Comment by thomasrliberto** [comment] 2020-06-24 18:59
@iainmcgin I finally got it working. I figured I'd let you all know in case anyone else runs into the same problem. It turns out all I had to do was set the scheme name for appAuthRedirectScheme to an entirely lower case string. So even though my Redirect URI is AppName:/callback, I had to set appAuthRedirectScheme to appname instead of AppName. This got it working. I appreciate the help!

**Comment by renuac** [comment] 2020-07-05 04:23
Lost My SIM

Em qua, 27 de mai de 2020 15:15, Iain McGinniss <notifications@github.com>
escreveu:

**Comment by VigneshKSI** [comment] 2020-07-20 07:58
Hi ,
Anyone can help me on this the above code is also not working as expected


I am getting error also like this in emulator

"No stored state - unable to handle response" and in AuthorizationManagmentActivity oncreate is returning null..



Can anyone Please help to solve this,I was trying this more than a months..

**Comment by VigneshKSI** [comment] 2020-07-21 06:51
START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=com.onmicrosoft.foodyhiveb2c.homefood://oauth/redirect?state=-FT_xh-aXUYotmYrqAPNPg&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..-tEFsilh2CezTpnn.qL-bLqCVs9u5MqRhRH7TM3PFYT-fDI_4Xslwq_k8y4Wnsp5ycoHLOqRQbr_oxmdw9iQHofITpaoLan2XDDOj4LwykJPL3Rrw86ItfPYdYu7u-qXHQSXTKR2MnvMStaEFzMjBaDqE8S1pf83fCiJzN-teEjptldRq1ZVmo_KJdcR2suuoH9BTDKkrf48JHDwO-6smlnSPGrfKIxnwqkqEbsZhwgs1cLxDKE1o8ylD0p0zX7GRqebToPFKhb1fyzKs44iik_EEcjAqiKjt4OHFCAZTg6NJ-mBfSdUWdsnmGoV232atGYwKdz9POXxmV4aczFYzx5yd32a9JLAYEZotVseYWZMp4tT90xhAOb_GXkNsL3Y3qiRHhMRznazgv9zeltJ1KrM7ibt_sMmpUOmkljIBMSg0HtOOggtnTWRuWq8lYddYvG8wNsUFxlOtWTdf1GrHbptXFQOy9AdiVoyQn-fSY-kpbfo_9H4a1IauzpeDteXHe0SwWgPhZptUNaz69-Qn9ZoK3S_L3TuTexuFrkIsBmKMigkyj2S_BGI-1b74n2qW4J1s0i4FnrB2ARdk6cywyUZR8uK1O-MIHyB84c-QkahK1he7fzQYIZvKtkx6WxvDpe9KjbdR5GtXPciu2Se5lKAngL571eG4vZOi_3kIpYNXbH8kW7dDLOqhUpTAorXc_305o2s4FTaIMBhyKxaREUhze-mtla4Wqr5ZWtRqSmXvoOuUCP7ncpZjUBBIy4oeXhreVHb2GUX67NiFY-Apthk.zI4OA-KCSfVVrdqvckeWvg flg=0x14000000 cmp=net.openid.appauthdemo/net.openid.appauth.RedirectUriReceiverActivity (has extras)} from uid 10113

**Comment by VigneshKSI** [comment] 2020-07-21 06:52
I am receiving this logs 


Then I am getting this Error

"No stored state - unable to handle response" and in AuthorizationManagmentActivity oncreate is returning null..

**Comment by VigneshKSI** [comment] 2020-07-21 06:52
Can anyone help ?

**Comment by VigneshKSI** [comment] 2020-07-21 07:13
When I use this Command 

adb shell am start -W -a android.intent.action.VIEW \
  -c android.intent.category.DEFAULT  \
  -d com.onmicrosoft.foodyhive.homefood://oauth/redirect



Status: ok
LaunchState: COLD
Activity: android/com.android.internal.app.ResolverActivity
TotalTime: 560
WaitTime: 614
Complete


When I use this 

adb shell am start -W -a android.intent.action.VIEW \
  -c android.intent.category.DEFAULT  \
  -d com.onmicrosoft.foodyhive.homefood:/oauth/redirect


Status: ok
LaunchState: WARM
Activity: android/com.android.internal.app.ResolverActivity
TotalTime: 513
WaitTime: 589
Complete




And For Both of this commands
I am getting this below Screen Only..


![Screenshot_1595315585](https://user-images.githubusercontent.com/37724418/88024089-c66b5800-cb4f-11ea-89de-37adacd42b87.png)

**Closed** 2020-08-03 03:43 UTC
Labels: question, redirect-handling
