### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by axnd** [openid/AppAuth-Android#298] opened 2017-11-20 20:06 UTC
I just noticed that in master the supportLibVersion is > 26 but in 0.7.0 it's still 25, any chance we can get a tag and release sometime soon so that I (and others) can start targeting v26?

**Comment by barbeau** [comment] 2017-12-22 21:36
I'd like to voice support for a new release w/ v26 of the support library as well.  We ([OneBusAway](https://github.com/OneBusAway/onebusaway-android)) are using the [EmbeddedSocial SDK](https://github.com/Microsoft/EmbeddedSocial-Android-SDK) which has a dependency on this library, and we have to use v26 of the support library in our app.  Android Studio 3.0 and higher flags this as an error in `build.gradle`.

cc @acrown-msft

**Comment by sunenielsen** [comment] 2018-04-24 07:06
Any plans for a new release? It's been half a year now.

**Comment by iainmcgin** [comment] 2018-04-29 21:50
I'm working out contributor license agreement issues with my new employer; hopefully that will happen soon, and then I can take control of this project again.

**Comment by CodyDunlap** [comment] 2018-06-14 18:00
+1 on new release. There are several issues that have been fixed but still waiting on a release.

**Comment by 0xbaadf00d** [comment] 2018-06-21 14:00
@iainmcgin Is it possible to have a new release. Important fix has been merged since august 2017 (ie: #309)

**Comment by pvegh** [comment] 2018-06-28 11:40
No answer. Project is dead.

**Comment by ve7jtb** [comment] 2018-06-28 12:14
I just talked to Ian yesterday.   The project is defiantly not dead.

I will work with him to sort out any issue caused by his change of employment.  
I know he is planning on continuing.

John B.

**Comment by CodyDunlap** [comment] 2018-08-06 17:27
@ve7jtb Any update on this? I've seen activity here and there from Ian but no response on this. I know there is activity but this project feels dead when we can't get any updates released for over a year.

**Comment by iainmcgin** [comment] 2018-08-08 00:59
The project isn't dead. We don't commit to any release schedule, and as far as I'm aware none of the patches we have taken in for the last year fix any significant bugs or issues, so that seems overstated.

Regardless, I'll get a new release out this week.

**Comment by iainmcgin** [comment] 2018-08-09 04:53
0.7.1 has been tagged and pushed to jcenter. I'm going to add instructions to the README on how to use jitpack to reference the library at any commit you like, to make it clear to everyone that we're not blocking anyone by not cutting "official" releases on some regular cadence.

**Closed by iainmcgin** 2018-08-09 04:53 UTC

**Comment by CodyDunlap** [comment] 2018-08-09 15:06
Thanks Ian! The #309 issue that I fixed was causing users to get kicked out of apps frequently because the library would return an AuthorizationException any time multiple requests that need a token refresh were fired in async. I'll be sure to use jitpack in the future if I'm waiting on a feature like this though. Thanks again!
