### ISSUE TITLE
App not automatically picking up the redirect to App Link url

### ISSUE THREAD

**Issue by MJMortimer** [openid/AppAuth-Android#527] opened 2020-04-02 20:24 UTC
Hey team,

I've just finished setting up an app and when the pop-up browser redirects back to the https URL that I've set up as an App Link my app won't automatically close the browser and continue onto the next activity.
If I click the context menu in the pop-up browser and select Open in chrome, then the disambiguation menu pops open and I can select my app and then it continues as expected.

It seems to work on an emulated android device, but not when running on my physical device.

Anything I might have missed?

**Comment by ferdau** [comment] 2020-04-09 09:44
Same issue here.

**Comment by adisazhar123** [comment] 2020-04-19 17:18
Same here, it works on an emulator. But once it's run on a physical device, the app doesn't close the browser activity. Any insights to why this is happening? I can provide more info if needed.

**Comment by hnljp** [comment] 2020-04-19 17:53
the problem is that you do not use your own custom uri scheme... if you use http or https as the uri scheme in the redirect uri, then if people have chosen that http or https uri schemes should always be opened on a specified browser, it will not work for your app anymore.

**Comment by adisazhar123** [comment] 2020-04-26 11:21
@hnljp Can you elaborate further? I have trouble understanding. We're using HTTPS.

**Comment by hnljp** [comment] 2020-04-26 12:00
> @hnljp Can you elaborate further? I have trouble understanding. We're using HTTPS.

Do like the demo app, and use the applicationId as its appAuthRedirectScheme
https://github.com/openid/AppAuth-Android/blob/0fbed7df170591bb4d9f20d5e7551e66aaabb4a3/app/build.gradle#L15

That will limit the possibility for other apps to catch the redirect uri.

So the demoapp is using something like:
net.openid.appauthdemo://[...]
where you are using:
https://[...]

**Comment by iainmcgin** [comment] 2020-05-27 18:32
@MJMortimer / @adisazhar123 Can you share your app manifest? In particular, I would like to confirm that the HTTPS URI you are using is correctly registered as an app link for your app. It has been a while since I've tested app links with AppAuth, I just want to confirm there has not been some significant change in handling of deep links like @hnljp seems to imply.

**Comment by gary-archer** [comment] 2020-06-08 21:46
Out of interest I used AppLinks for a recent Kotlin code sample of mine. AppAuth libraries work fine but you need an interstitial page to receive responses, as in [Iain's Advanced Sample](https://github.com/iainmcgin/AppAuth-Demo) and it is pretty tricky.

[Android Code Sample](https://github.com/gary-archer/authguidance.mobilesample.android)
[Android Blog Post](https://authguidance.com/2019/09/13/android-code-sample-overview/)

**Comment by cpednekar** [comment] 2020-10-29 11:00
> 
> 
> the problem is that you do not use your own custom uri scheme... if you use http or https as the uri scheme in the redirect uri, then if people have chosen that http or https uri schemes should always be opened on a specified browser, it will not work for your app anymore.

some oauth2 providers like Shopify for example mandate redirect url to have https or http schemes. 
Their portal does not accept any scheme at all. 
And that's where it redirects to after auth..

**Comment by agologan** [comment] 2020-12-08 08:45
The other contributors have correctly pointed out that for https links to work, you need to correctly define an AppLink otherwise these will be handled by your default browser association.

As @gary-archer suggested it's also possible to have a hosted service which receives your https redirect and than transforms that request into your custom redirect uri.

Closing this issue as neither reporters have replied since originally posted in April.
Feel free to open a new issue if it still doesn't work providing an example configuration that we can look at.

**Closed by agologan** 2020-12-08 08:45 UTC
Labels: question, redirect-handling
