### ISSUE TITLE
updating to 0.8.0, Authorization failing on below 11

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [openid/AppAuth-Android#693] opened 2021-04-23 09:12 UTC
Hi team,

We have upgraded appauth lib to latest 0.8.0 to support Andorid 11, but now it is not working on Android 10 and below.
Throwing below exception.
`AuthorizationException: {"type":0,"code":9,"errorDescription":"Invalid ID Token"}`

Stacktrace:
```
Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-04-23 14:53:26.044 5952-5952/tech.wordly.android.attend W/System.err: AuthorizationException: {"type":0,"code":9,"errorDescription":"Invalid ID Token"}
2021-04-23 14:53:26.045 5952-5952/tech.wordly.android.attend W/System.err:     at net.openid.appauth.IdToken.validate(IdToken.java:183)
2021-04-23 14:53:26.045 5952-5952/tech.wordly.android.attend W/System.err:     at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:698)
2021-04-23 14:53:26.046 5952-5952/tech.wordly.android.attend W/System.err:     at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:564)
2021-04-23 14:53:26.046 5952-5952/tech.wordly.android.attend W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:755)
2021-04-23 14:53:26.047 5952-5952/tech.wordly.android.attend W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:192)
2021-04-23 14:53:26.047 5952-5952/tech.wordly.android.attend W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
2021-04-23 14:53:26.047 5952-5952/tech.wordly.android.attend W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2021-04-23 14:53:26.048 5952-5952/tech.wordly.android.attend W/System.err:     at android.os.Looper.loop(Looper.java:214)
2021-04-23 14:53:26.048 5952-5952/tech.wordly.android.attend W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7397)
2021-04-23 14:53:26.048 5952-5952/tech.wordly.android.attend W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-23 14:53:26.049 5952-5952/tech.wordly.android.attend W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-04-23 14:53:26.049 5952-5952/tech.wordly.android.attend W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2021-04-23 14:53:26.050 5952-5952/tech.wordly.android.attend W/System.err: Caused by: net.openid.appauth.IdToken$IdTokenException: ID Token expired
2021-04-23 14:53:26.051 5952-5952/tech.wordly.android.attend W/System.err: 	... 12 more
2021-04-23 14:53:26.099 5952-5952/tech.wordly.android.attend W/.android.atten: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-04-23 14:53:26.124 5952-5952/tech.wordly.android.attend W/.android.atten: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-04-23 14:53:26.125 5952-5952/tech.wordly.android.attend W/.android.atten: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
2021-04-23 14:53:26.125 5952-5952/tech.wordly.android.attend W/.android.atten: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-04-23 14:53:26.205 5952-5952/tech.wordly.android.attend I/chatty: uid=10516(tech.wordly.android.attend) identical 2 lines
```

Any changes required wirth latest version?

Thanks

**Comment by agologan** [comment] 2021-04-23 14:36
Since `0.8.0` there are ID Token validations in this case:
`Caused by: net.openid.appauth.IdToken$IdTokenException: ID Token expired`

In your case it's either expected or there's an issue with your identity provider.

**Comment by bhuvaneshwariarkala** [comment] 2021-04-25 15:12
What is identity provider. The same thing works on Android 11, but not on below 11.

**Comment by agologan** [comment] 2021-04-26 07:57
There is not enough information here to help you, but have you checked the device time?
You can also breakpoint into that check and look at the exact values.

**Comment by MKevin3** [comment] 2021-07-20 19:24
This has bitten me at a past job and is now biting me again. Last job I pulled down the full source code, made it into a module, commented out rule #9 and rule #10 so it would work for all our clients. Looks like I get to do the same thing again.

IdToken.java lines 172 to 187 have to be commented out. Would be nice if you could pass in which rules you want enforced instead of having them all win.

**Comment by agologan** [comment] 2021-07-21 12:03
@MKevin3 can you please explain what the actual problem is/was?
I'm open to make changes to those validations given a reasonable explanation.

**Comment by MKevin3** [comment] 2021-07-21 12:29
We have people in the field that keep getting error #9 which is the code below. This happened to me at my last job as well. At the last job our local server / WiFi provider was off by 2 minutes (slow I think) which annoyed the heck out of my phone in general. We would get this error all the time so I had to comment out the code as you could not log in at all. It was killing me because there was no network traffic, just an error which I finally tracked down to this code.

From a standards point of view I get why this check is there but it is either WAY too picky on the time or just not useful at all. With it commented out things have run fine for years at old gig and for over a year at current job.

For the current job I don't get to directly interact with people in the field. These are car sales folks and who knows how they have their device time configured or what is going on with the dealerships servers and WiFi times. I can't fix either of those issues so I comment out both the #9 and #10 error validations so we can keep them working.

Just last week I had forgotten about all that work as I did it years ago. We decided we wanted to be on latest version of this library so we tossed the module and directly did "implementation" and now I get to do a hot-fix today after converting the latest code out here to a module again and commenting out #9 and #10

```
        Long nowInSeconds = clock.getCurrentTimeMillis() / MILLIS_PER_SECOND;
        if (nowInSeconds > this.expiration) {
            throw AuthorizationException.fromTemplate(GeneralErrors.ID_TOKEN_VALIDATION_ERROR,
                new IdTokenException("ID Token expired"));
        }

```

**Comment by pvegh** [comment] 2021-08-23 14:15
We also faced issues and we had to fork AppAuth to disable the time check. This should be an opt out here in our opinion.

**Comment by agologan** [comment] 2021-11-26 12:29
@MKevin3 agree this lib doesn't deal well with clock skew and we could improve.
In most cases this shouldn't have a major impact unless you rely only on `performActionWithFreshTokens` and `getNeedsTokenRefresh` as explained here: https://github.com/openid/AppAuth-Android/issues/747

Closing this item. Recommend you write a feature request or propose a merge request for either clock skew as explained in the OpenID spec or about a more resilient authentication flow.

**Closed by agologan** 2021-11-26 12:29 UTC
Labels: question
