### ISSUE TITLE
Slow authorization if used in UI Thread

### ISSUE THREAD

**Issue by CosimoSguanci** [openid/AppAuth-Android#389] opened 2018-07-28 16:20 UTC
Hi, if I try to run this code on the UI Thread

    AuthorizationServiceConfiguration serviceConfig =
                        new AuthorizationServiceConfiguration(
                                Uri.parse("https://accounts.noku.io/api/oauth2/authorize"),
                                Uri.parse("https://accounts.noku.io/api/oauth2/token"));

                AuthorizationRequest.Builder authRequestBuilder =
                        new AuthorizationRequest.Builder(
                                serviceConfig,
                                "noku-mobilewallet",
                                ResponseTypeValues.CODE,
                                Uri.parse("io.noku.app.nokuwallet:/oauth2redirect"));

                AuthorizationRequest authRequest = authRequestBuilder
                        .build();

                AppAuthConfiguration appAuthConfig = new AppAuthConfiguration.Builder()
                        .setBrowserMatcher(new BrowserWhitelist(
                                VersionedBrowserMatcher.CHROME_CUSTOM_TAB))
                        .build();

                authService = new AuthorizationService(settingsActivity, appAuthConfig);
                Intent authIntent = authService.getAuthorizationRequestIntent(authRequest);
                startActivityForResult(authIntent, 143);

The authorization flow is really slow (the custom tab opens after 1/2 seconds). I tried to run this code on  a separate thread and now it runs perfectly. I think you should add this to the docs!

**Comment by iainmcgin** [comment] 2018-08-08 00:06
[Duplicate of #328]

The `AuthorizationService` class attempts to create a service connection to the browser to make launching the tab faster, but this only works well if you create the AuthorizationService before you need it as you seem to be doing above. I recommend splitting up your above code, in order to create your `authService` in response to `onStart`. I'll try and do a better job of documenting this, thanks for reporting your issue!

**Closed by iainmcgin** 2018-08-08 00:06 UTC
