### ISSUE TITLE
response_mode=fragment not supported

### ISSUE THREAD

**Issue by mateuszwlodarczyk265** [openid/AppAuth-Android#216] opened 2017-04-17 08:04 UTC
Hi! 

Please correct me if I'm wrong but it seems that AppAuth-Android doesn't support response_mode=fragment, although its default response_mode for most response_type's. The problem is that according to this [documentation](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations) point

>  5.  Definitions of Multiple-Valued Response Type Combinations

 response_mode shouldn't be changed to 'query' when by default is 'fragment'. Does development team plans to include 'fragment' response mode in authorisation response?

**Comment by iainmcgin** [comment] 2017-04-18 23:47
Duplicate of #75. In short, we're not against supporting response_mode=fragment, though we are not prioritizing implementing it. If you wish to send us a PR to add support for this, I'd be happy to review it.

**Closed by iainmcgin** 2017-04-18 23:47 UTC
