### ISSUE TITLE
Refreshing an access token crash - JSONException: field "token_type" not found in json object

### ISSUE THREAD

**Issue by chrisstj** [openid/AppAuth-Android#233] opened 2017-05-25 07:57 UTC
Hello guys.

I am developing an Android application and I am using the AppAuth-Android sdk for login and getting tokens.

The access token that I get from the TokenRequest after login expires in 10 hours. Because of this I have to refresh it.
The problem occurs when performing a new TokenRequest. I invalidate the access token and afterwards I make a new TokenRequest with the following parameters:
- authorizationCode 
- refreshToken
- scope, which is set to “openid”
- grantType, which is set to “refresh_token”,

and i get the following error:
```
Process: de.telekom.android.seamlessconnectivity_mk, PID: 9261
java.lang.IllegalStateException: JSONException thrown in violation of contract
at net.openid.appauth.TokenResponse$Builder.fromResponseJson(TokenResponse.java:227)
at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:397)
at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:299)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: org.json.JSONException: field "token_type" not found in json object
at net.openid.appauth.JsonUtil.getString(JsonUtil.java:171)
at net.openid.appauth.TokenResponse$Builder.fromResponseJson(TokenResponse.java:209)
at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:397) 
at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:299) 
at android.os.AsyncTask.finish(AsyncTask.java:632) 
at android.os.AsyncTask.access$600(AsyncTask.java:177) 
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5538) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Did any of you encounter this issue?
Maybe you could help me somehow.

Thank you and best regards,
Chris

**Comment by iainmcgin** [comment] 2017-05-25 21:22
The crash is caused by #228; the fix for that part has been merged and will be released as part of 0.6.1. However, your description of acquiring a new token does not sound correct, which is probably the root cause: you should not need to send an authorization code again, this value should be consider one-time-use. See [Section 6](https://tools.ietf.org/html/rfc6749#section-6) of the OAuth2 specification.

Furthermore, The AuthState class provides the "performActionWithFreshTokens" method, so you should not need to manually refresh your access tokens.

**Comment by chrisstj** [comment] 2017-05-26 07:11
Hi. 
I have update my code and now I use the performActionWithFreshTokens() method from AuthState to get a new access token, but if I set the setNeedsTokenRefresh(true) then I get the same crash as noted above.
I will remove the setNeedsTokenRefresh(), but do you know when the 0.6.1 version will be available?

Best regards,
Chris

**Comment by chrisstj** [comment] 2017-05-29 08:19
Hi.
Any news on when the new version, 0.6.1 will be released?
Thanks,
Chris

**Comment by iainmcgin** [comment] 2017-05-31 00:37
I just released it; you should be able to update now.

**Comment by chrisstj** [comment] 2017-05-31 08:41
Hi.
I have updated the sdk in my project but now if I make a new TokenRequest, then the tokenResponse is null, so I cannot get a new access token.
I used the authstate.performactionwithfreshTokens() method but that gives me an access token that is already expired.

Do you know what can I do in this case?

Thank you,
Chris

**Comment by iainmcgin** [comment] 2017-05-31 21:57
As I mentioned earlier your token request is likely malformed. Without more information on the authorization server you are integrating with and the request / response bodies, I can't help you much more.

**Comment by chrisstj** [comment] 2017-06-06 08:54
Hi.
I use the AuthorizationService from openid.appauth to perform token requests.
The first request for an access token is after the first authorization response, and I make the request as follows:

final AuthorizationResponse lastResponse = authState.getLastAuthorizationResponse();
            tokenRequest = new TokenRequest.Builder(lastResponse.request.configuration, lastResponse.request.clientId)
                    .setGrantType("refresh_token")
                    .setRefreshToken(authState.getRefreshToken())
                    .build();

final CountDownLatch tokenLatch = new CountDownLatch(1);
        try {
            mAuthService.performTokenRequest(tokenRequest, authState.getClientAuthentication(), new AuthorizationService.TokenResponseCallback() {
                @Override
                public void onTokenRequestCompleted(@Nullable TokenResponse tokenResponse, @Nullable AuthorizationException e) {
                    mTokenResponse = tokenResponse;
                    tokenLatch.countDown();
                }
            });
            tokenLatch.await();
} catch (UnsupportedAuthenticationMethod | InterruptedException e) {
            return null; 
        }

This first request for the access token works well and I get a valid access token.
When I do it again, the mTokenResponse is null.

Do you know what could be wrong with this approach?
Chris

**Comment by chrisstj** [comment] 2017-06-08 08:30
Hi.
I noticed that when using AuthState.jsonDeserialize(json) before making the first token request, the token_type is null as well and I do not get this error, but at the second token request this error appears.
Do you know why this happens?

Best regards,
Chris

**Comment by iainmcgin** [comment] 2017-06-13 00:59
`token_type` is a required response field, so I'm not sure what your IDP is doing. Are you sure you're getting a valid response?

**Comment by chrisstj** [comment] 2017-06-13 06:25
I am not getting a valid respone, 
On the AuthorizationService.TokenResponseCallback(), in the onTokenRequestCompleted method I get a null TokenResponse and the exception {"type":0,"code":5,"errorDescription":"JSON deserialization error"} with the cause "field "token_type" not found in json object".

After debugging I have noticed that even for the first request, the token_type field in the response is null and I don't get the error, but I get it for the second request.

Is it supposed to be like this?
Best regards,
Chris

**Comment by iainmcgin** [comment] 2017-07-05 15:29
If you are not getting a valid response from the identity provider, there is little that AppAuth can do to help in this situation. I suggest you contact the maintainers of the identity provider to diagnose and fix the issue.

**Comment by jaychang0917** [comment] 2017-07-13 07:20
I encountered the same issue that `token_type` is not found exception.  The identity provider is Instagram. The response is
```
{
    "access_token": "fb2e77d.47a0479900504cb3ab4a1f626d174d2d",
    "user": {
        "id": "1574083",
        "username": "snoopdogg",
        "full_name": "Snoop Dogg",
        "profile_picture": "..."
    }
}
```

Have any solutions?

Thanks

**Comment by chrisstj** [comment] 2017-07-13 07:37
I have found the solution yesterday and the problem was that I always used for the new token requests(if the access token expires) the refresh token that I got after login.
The solution was to always use for the new token requests, the refresh token that I have got from the previous token request.
The new refresh token you can take from the tokenResponse.

Hope it helps.

Best regards,
Chris

**Comment by iainmcgin** [comment] 2017-07-13 08:18
@jaychang0917 it looks like the Instagram response does not comply with the OAuth2 spec. Please report this to Instagram as they claim to be OAuth2 compliant. In the meantime, you'll need to fork AppAuth and add Instagram specific code to inject the missing token_type value.

**Closed** 2017-07-13 08:19 UTC
Labels: provider-bug, question

**Comment by bbqsrc** [comment] 2018-01-26 16:08
Surely it is not unreasonable to add a mode to opt into blindly accepting malformed responses?

Instagram is not ever going to fix their implementation and this is now a blocker. :smile:
