### ISSUE TITLE
AppAuth issue on Android 12

### ISSUE THREAD

**Issue by petruswang** [openid/AppAuth-Android#769] opened 2021-11-30 06:36 UTC
### Configuration
- Version: 0.10.0
- Integration: native Java
- Identity provider: Custom

### Description
Hi all! Thanks for maintaining this project.
I've used AppAuth with native Java integration in a project for years and it's been working great. Using the startActivityForResult variant. However, the lastest build that has been working on all Android versions for a long time, doesn't work on Android 12. It behaves like user cancelled login attempt, even though user authenticated successfully.
Upon closer investigation and debugging, it seems that on Android 12, in AuthorizationManagementActivity, after authentication, the method onResume is called before onNewIntent, so the new intent data is never picked up and returned as expected.

* Can anyone else confirm the issue?
* Any known work around/fix or suggestions on what can be done?

Thank you

**Comment by ssinha979** [comment] 2021-12-07 22:24
Hello @petruswang,

We have the same problem. It is reproducible on a Pixel 4a device running Android 12.
Did you figure out a way to get around this issue?

Thank you.

**Comment by shahfaizal** [comment] 2021-12-08 06:06
Hello @petruswang,

We have the same problem. It is reproducible on a One Plus  LE2121  &  Pixel 3a XL device running Android 12. But same things works fine with android 11 and below.

 @ssinha979

**Comment by petruswang** [comment] 2021-12-08 09:04
I am testing a simple work around in this fork:
https://github.com/openid/AppAuth-Android/compare/master...petruswang:android12_newintent_fix?expand=1

**Comment by Babulaandroid** [comment] 2021-12-08 09:08
I am also facing same issue in Android 12 device.

**Comment by petruswang** [comment] 2021-12-08 21:46
Hi @ssinha979 
This is what I did:
1. Clone the App-Auth repo
2. Open the project in Android Studio
3. Chose Build->Make Module 'AppAuth-Android.library'
4. In "Build Variants", you can change between "debug" and "release" build variants
5. Find the library files (aar) in file system under AppAuth-Android/library/build/outputs:
appauth-debug.aar
appauth-release.aar
6. Move one or both of these into your project, into a folder "libs" at the same level as "src"
7. In your build.gradle, under dependencies, add one or both of:
    releaseImplementation files('libs/appauth-release.aar')
    debugImplementation files('libs/appauth-debug.aar')
8 Comment out the // implementation 'net.openid:appauth:0.10.0'

That should do it!

**Comment by ssinha979** [comment] 2021-12-08 21:50
Thanks @petruswang 
I finally figured out that I was trying to include the demo-app all along and that's why it was failing.
These detailed steps will help me make it work.
I'll report back when I have results.

Cheers :)

**Comment by agologan** [comment] 2021-12-09 09:23
@petruswang Haven't seen the issue you're describing and can't find any reports in the google issuetracker.
The described behaviour would be an SDK bug because according to the docs `You can count on onResume() being called after this method` ref: https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent) 

That's not to say this isn't a real issue but maybe it's rooted somewhere else.
Can you reproduce this issue in the context of an emulator and/or the demo app?

Also took a look at your workaround and that wouldn't be enough unless you get `onResume` called twice.
If the ordering is wrong you'd have to add 2 flags, passed onResume and passed onNewIntent , and when both are true handleAuthorization*().

**Comment by petruswang** [comment] 2021-12-09 09:53
Hi @agologan 

Yes, you are probably right in that the issue is likely rooted somewhere else. Also, it's not that the call order is wrong. It's that on Android 12 (tested in simulator and device) onResume gets called once before onNewIntent (not expected), and then again after (expected). At least within the scope of AppAuth-Android 0.10.0. Not sure if this would count as a SDK bug, as I don't think it is stated that onResume cannot also be called before onNewIntent.

I have confirmed the fix working in simulator and a phone (when it didn't before with AppAuth-Android 0.10.0) and testing it now with a larger audience.

**Comment by agologan** [comment] 2021-12-09 18:12
Do you mind testing this in the demo app? Not seeing the same testing in the sdk31 emulator.

**Comment by petruswang** [comment] 2021-12-09 19:35
I did a quick test with the demo app towards an okta dev account. I don't see the behaviour there either.
Don't immediately know what the differences are.
Did my AppAuth integration years ago. May need to revisit that again and check what can be updated.
However, something has changed with Android sdk31, since it has and still works well up to sdk30.
Will update if and when I find any additional clues.

**Comment by ssinha979** [comment] 2021-12-09 20:55
Hello,
It took me a while to get back. Had to fix other build issues with the upgrade to SDK31.
I can still reproduce the bug on the Pixel 4a with @petruswang 's fix.
I too can confirm that something changed in SDK 31 since the same code works with SDK 30.

**Comment by ssinha979** [comment] 2021-12-13 16:12
Hi guys,

So I tested it with the AppAuth demo app with Okta and I'm not able to reproduce the bug both with and without @petruswang 's fix.
Could someone clarify what the next steps are? Maybe we need to report to Google if it really is an SDK issue?
I'd like to hear your thoughts on how we are to tackle this.

Thank you.

**Comment by petruswang** [comment] 2021-12-13 17:16
I had quite some issues debugging this on Android 12 simulator. Turned out the issue was likely with the AVD. Created a new AVD with system image "Android 12 x86_64 (Google Play)". Now I cannot reproduce the issue (or any issue) anymore in emulator.
However, login issue was originally reported to me by a user with Android 12 phone. She has tested a version with my "fix" and confirmed it working. I will keep using my fix until I can get a physical Android 12 myself to test on.

@ssinha979 Did you get things to work with my fix?  If so, I suggest you use that for now until we get a clear picture of what is happening. If not, can you reproduce the issue on emulator? Please provide more info on your findings.

**Comment by ssinha979** [comment] 2021-12-13 18:22
Hi @petruswang 
I can still reproduce the issue on my physical device (Pixel 4a) with your fix.
But on an emulator is works well.

I would've used this fix for the time being if it worked on my device, but sadly it still happens :(

**Comment by petruswang** [comment] 2021-12-13 18:29
@ssinha979 As I cannot reproduce the issue now, I cannot really help you.
I suggest you do some debugging with your device and try to figure out what is happening. If you provide some details, maybe I or someone else can help.
If or when I encounter and can reproduce this issue again, I'll post updates here.
Good luck!

**Comment by ssinha979** [comment] 2021-12-13 18:48
Thanks @petruswang . I appreciate your help. 
I was counting on being able to reproduce the problem on the AppAuth demo app in order to debug it but I couldn't.
Let me see what I can do.

**Comment by petruswang** [comment] 2021-12-15 06:28
Hi @Harkertron 
Thanks for sharing this! I've done some quick tests, and it is as you described for my project. This now makes much more sense.
In my case, letting AuthorizationManagementActivity handle all configChanges by specifying in manifest works and feel like a good solution. I tested using the default AppAuth 0.10.0, now without issues.

TL:DR;
Add/change to the following in your app manifest:
```
        <activity
            android:name="net.openid.appauth.AuthorizationManagementActivity"
            android:configChanges="orientation|keyboardHidden|screenSize|smallestScreenSize|screenLayout"
```

**Comment by ssinha979** [comment] 2021-12-15 14:23
Hi guys,

Thanks for sharing those insights @Harkertron.

So we found [this](https://github.com/openid/AppAuth-Android/issues/746) workaround.
We basically refactored our code to use pendingIntents with the MUTABLE flag instead of startActivityForResult.
Now it works well on the physical device :)

**Comment by Harkertron** [comment] 2021-12-16 13:52
Hey folks, 

@ssinha979, yep, we considered refactoring to use the **pendingIntents** flow instead, and saw that other issue at the time. Good to know its working with that other MUTABLE flag fix for you. :) 

On our end, more users were attempting to login using Pixel 6's, so we had a need to get a fix out quickly, plus we were wary of potentially introducing new issues on other devices from such a refactor to use the alternative flow.

With this in mind went for this config fix for the **startActivityForResult** flow so we could fix in our manifest without potentially forking appauth. 

@petruswang, yep, that's pretty much what we added to our manifest entry, as mentioned above ideally that would be in the appauth lib's manifest entry itself, what do you think, @agologan?

Best wishes, 

Jon Harker

**Comment by agologan** [comment] 2021-12-16 14:37
While I've been fairly silent on this topic I do appreciate all the research that has gone into identifying the issue and a workaround.
I initially wanted to roll with the `configChanges` patch including all the possible values since any of those could potentially cause this issue.
Upon further consideration I've been reflecting if there are other use-cases where the issue may occur and there most probably are.

So I'm at the point thinking if there's a better way to fix and protect against these scenarios?

**Comment by Harkertron** [comment] 2021-12-18 16:58
Perhaps. From what I recall (sadly not near my equipment currently for testing), the bug only exhibited if the orientation changed just after the AuthorizationManagementActivity was invoked. If we had the app in auto-rotate mode and changed the orientation a few times while the web browser was open - but before completing login - there would be no issue so long as the final browser orientation matched our own locked app orientation. 

This was why we didn't add the other configConfig changes in our manifest. (For things like language update, it seemed infeasible that could update in that small Xms time window.) 

At the point it's triggering the restart - it is killing (via onDestroy) the AuthorizationManagementActivity, though it is at a point where the credentials are still valid, so it is possible to grab them out, but we couldn't figure out a way to get it working without inadvertently breaking the cancel flow and a few unit tests.

I think previously it wasn't even triggering this configChanges restart. There is some precedent of this happening with camera apps - where the app is doing the rotating with it's created activities - not the physical device. 

https://stackoverflow.com/questions/15019892/handling-orientation-change-on-camera-intent/15020468

Perhaps something has changed under the hood in the Android OS, to cause this to trigger for web browsers. Not sure I'd call it a 'bug' since it's doing what the spec says on the configChanges page of the Android Activity Life cycle I linked earlier.

Best wishes,

Jon Harker

**Comment by agologan** [comment] 2021-12-22 17:09
Decided to integrate the proposed change and released a new version as `0.11.1`.
This issue isn't completely resolved, more like mitigated for now.
Long term unless this gets fixed in Android we need to change the way we relate to that activity's lifecycle.

Closing for now. Feel free to leave a comment if you run into other use-cases besides the ones mentioned above.

**Closed by agologan** 2021-12-22 17:09 UTC
Labels: question

**Comment by JontyMC** [comment] 2022-03-01 09:17
Is 0.11.1 supposed to have fixed this issue? I'm seeing it with 0.11.1 when phone has been locked and opening app again. The app gets into a state where user enters valid credentials, but logging says "user cancelled flow" and another auth window pops up.

**Comment by carstenhag** [comment] 2022-05-03 15:21
@JontyMC With what phone & android version did that occur?  
Did someone else notice this behavior? I did not, yet.

**Comment by JontyMC** [comment] 2022-05-03 15:35
Galaxy S9 Android 10. Not exactly sure of the reproduction for this. It seems to be related to locking, but only happens occasionally, and generally after phoned has been locked for a while. It's possible its something to do with how we have coded it, but I don't think we are doing anything out of the ordinary.

**Comment by dattran-pt19** [comment] 2022-11-16 10:50
My app only use getAuthorizationRequestIntent(request), no PendingIntent but it's come with error after close CustomTab and call API. Any one have the same issue? :((
