### ISSUE TITLE
Prompt : 'select _account' not working for google authentication, but works on  Microsoft AD as Prompt : 'Login'

### ISSUE THREAD

**Issue by Saitarak436** [openid/AppAuth-Android#680] opened 2021-04-07 11:35 UTC
### Checklist:

- [x] I am using the latest release
- [x] I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x] I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [ ] I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [ ] I am either using a custom URI scheme or `https` with (App Links)[https://developer.android.com/training/app-links] for client redirect.
- [ ] I can reproduce the issue in the demo app (optional)

### Configuration
- Version: 0.X.Y
- Integration: (native(Java/Kotlin), Xamarin, ReactNative, etc)
- Identity provider: (Google, Okta, Gluu, Auth0, KeyCloack, etc)

**Comment by agologan** [comment] 2021-04-08 16:21
Closing as duplicate of #681

**Closed by agologan** 2021-04-08 16:21 UTC
Labels: bug
