### ISSUE TITLE
The "launchMode" of AuthorizationManagementActivity is "singleTask", Which makes apps with multiple processes and taskAffinity hard to manage. Thanks.

### ISSUE THREAD

**Issue by Smao0875** [openid/AppAuth-Android#170] opened 2017-02-18 22:56 UTC
My application is a little bit complicated:
app A runs at UI to render all data.  (assuming taskAffinity is A)
app B runs at background as a service to provide all data and account setup related activities. (assuming taskAffinity is B).
A and B are running on different processes.

Now A launches activities in B to add a Google Account, the activity stack is now:
TASK1: A -> B.
From B we are going to launch AuthorizationManagementActivity to do all authentication work.
Because the **launchMode** of AuthorizationManagementActivity is **singleTask** and the **taskAffinity** of AuthorizationManagementActivity is B, we get following activity stacks:
TASK1: A -> B.
TASK2: AuthorizationManagementActivity -> CustomTabActivity.

Which makes it very hard to manage my activity stacks and tasks.
Should I just folk the code and remove the following line?
android:launchMode="singleTask"

Is there any suggestions to solve my problem?

Thanks a lot.

**Comment by iainmcgin** [comment] 2017-02-19 21:59
We use singleTask so that the [RedirectUriReceiverActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/RedirectUriReceiverActivity.java#L56) can send the captured result to the existing instance of [AuthorizationManagementActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L206), which retains the original AuthorizationRequest, validates the response, and then removes the items above it in the back stack through calling finish(). This is explained more thoroughly in the [javadoc](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L31) for AuthorizationManagementActivity.

We tried using `singleInstance` instead of `singleTask`, but this causes problems when not using custom tabs, as the browser is created in its own task and `singleInstance` will then allow a new `AuthorizationManagementActivity` to be created within that task's context, and we lose the necessary context to return the result.

In an earlier version of AppAuth we used to retain the AuthorizationRequest in a static (in-memory) store, which meant that we didn't need the launchMode gymnastics to recover the request. This caused problems if the requesting app process was killed due to memory pressure. A solution to that would have been to store data on disk using a SharedPreferences file, however we have done 

This SharedPreferences approach could probably work for you, but it's not something I wish to officially support in the library unless there is more demand for it - we have done everything we can so far to avoid having the library manage persistent state.

**Comment by Smao0875** [comment] 2017-02-20 01:54
@iainmcgin 
Thanks again for your quick reply :)

My current activity stack looks like (the launchMode of AuthorizationManagementActivity is "singleTask"):
Task1: (process A -- UI) MainActivity -> (process B -- service) AccountSetupActivity (startActivityForResult) -> OAuthActivity
Task2: AuthorizationManagementActivity -> CustomTabActivity

My OAuthActivity also handles result or cancel event from OAuth, so I need to get back to OAuthActivity after we finished or canceled AuthorizationManagementActivity.

Question 1:
Is there a way to bring OAuthActivity in Task1 to foreground after we finished or canceled AuthorizationManagementActivity?
I tried to define the launchMode of OAuthActivity to "singleTask" but didn't work.

Question 2:
I assume the SharedPreferences approach should work like:
1. in handleAuthorizationComplete() and handleAuthorizationCanceled() write result into SharedPreference.
2. Bring OAuthActivity to foreground to read SharedPreference and act accordingly?
 -- However I couldn't find a way to bring a task to foreground in handleAuthorizationComplete() or handleAuthorizationCanceled().
    The only thing I can do is to set **MainActivity** launchMode to "singleTask" then launch it from handleAuthorizationComplete() or handleAuthorizationCanceled(). But what if use adds account from android settings? then the activity stacks are:

Task1:  (Anroid OS) Settings -> (Anroid OS) SubSettings -> (Anroid OS) SubSettings ->  AccountSetup -> OAuthActivity
Task2:  AuthorizationManagementActivity -> CustomTabActivity

I don't think I have any right to overwrite **Settings**

I am a little bit confused. -- I think I am doing something terribly wrong because AuthorizationManagementActivity always starts in a new task.

Thanks a lot.

**Comment by mattinger** [comment] 2017-02-27 19:25
@iainmcgin I'm encountering what i think is a related issue.  I will note that i have not been able to pinpoint the cause just yet.  But here's what happens:

We have a LoginActivity that calls the AuthorizationService to start the login.  It goes through the normal flow, and when UriRedirectReceiver sends the intent back to AuthorizationManagementActivity, it's going through the "onCreate" method, and not onResume.  I presume somehow, either the AuthorizationManagementActivity is getting destroyed, or we're ending up on a separate task.

As i said, i can't pinpoint yet why this is happening.  Any suggestions on how to figure this out?

**Comment by Smao0875** [comment] 2017-02-27 20:02
Hi, @mattinger 
Can you give more info on your issue?
Such as your activity stack?
Do you know how to dump the activity stack ?
http://stackoverflow.com/questions/4387875/view-activity-stack-in-android

Thanks

**Comment by mattinger** [comment] 2017-02-27 20:35
I'm trying to produce it again.  It doesn't happy very often :(   I'm asking our QA team to see if they can get it in that state again.

**Comment by Smao0875** [comment] 2017-02-28 16:06
Hi, @iainmcgin 
I already fixed my problem.
Should we lose this thread?

**Comment by iainmcgin** [comment] 2017-02-28 18:31
I'll close this issue, thanks. @mattinger if you manage to reproduce your problem, feel free to open a new issue.

**Closed by iainmcgin** 2017-02-28 18:31 UTC
Labels: question

**Comment by nuxusr** [comment] 2017-10-03 17:15
FYI - Really strange but I'm able to reproduce what @mattinger is seeing every time if I put a breakpoint in the onCreate of RedirectUriReceiverActivity. Not sure how this breaks the singleTask, but I get a new instance when I try and walk through on the debugger.  

First time through taskId is 92 and object instance #6636:
![image](https://user-images.githubusercontent.com/34004/31138132-a9e2d9ba-a82a-11e7-860e-f5e4baef05ed.png)

After the redirect relaunches the Activity (while debugging) taskId is 94 and object instance #6835:
![image](https://user-images.githubusercontent.com/34004/31138157-c4f0bf06-a82a-11e7-8bcf-afa5de8908f1.png)

I've attached my activity stack here where you can also see the two instances.
[activity task stack.txt](https://github.com/openid/AppAuth-Android/files/1353226/activity.task.stack.txt)

Is it because the activity that kicks off the flow also has a singleTask?

**Comment by nuxusr** [comment] 2017-10-03 17:32
Sorry just saw the other open bug on this (182). I'll see if the suggestions there help
