### ISSUE TITLE
Config Access denied

### ISSUE THREAD

**Issue by rahulsingh0089** [openid/AppAuth-Android#202] opened 2017-03-21 10:37 UTC
After importing app-auth aap in nadroid studio then getting error ---
AppAuth-Android-master\config (Access is denied)

Please check, why we getting this problem.

**Comment by iainmcgin** [comment] 2017-03-22 19:05
Duplicate of #195.

**Closed by iainmcgin** 2017-03-22 19:05 UTC

**Comment by rahulsingh0089** [comment] 2017-03-23 04:22
See the complete log

[idealog.txt](https://github.com/openid/AppAuth-Android/files/863601/idealog.txt)
