### ISSUE TITLE
Application getting closed

### ISSUE THREAD

**Issue by Mayranit** [openid/AppAuth-Android#112] opened 2016-10-04 18:13 UTC
I have a app which uses AppAuth library to support SSO. When I clear data/cache of the app and reopen the app again, App is getting closed for the first time, when i launch it again, app opens without any issue.
1. Login to the app with credentials.
2. Go to Settings -> Application Manager  then clear DATA.
3. Now try open the application.

Applications opens and immediately get closed (No error / Crash).

Code where I am facing this issue.

authService.performAuthorizationRequest(
                req,
                PendingIntent.getActivity(this, req.hashCode(), postAuthIntent, 0));

**Comment by iainmcgin** [comment] 2016-10-04 20:22
I don't know how this could be caused by the library - we don't write any state to disk, so clearing data doesn't affect it. I can't help you unless you're able to provide a stack trace of a failure, or logs of what happened, or code to see how you are using the library.

**Comment by Mayranit** [comment] 2016-10-05 17:16
Hi , I have attached code and logs. MainActivity.java is entry point for my application. When i call "performAuthorizationRequest" it takes input. It executes all the lines. App gets closed when the last line "this.mContext.startActivity(intent);" gets executed.  

It should open PostAuthActivity.java. I had a break point and logs at Oncreate of "PostAuthActivity", but it never get excecuted.

This issue happens only once. Only first time after clearing cache of the application.

[codeAndlogs.zip](https://github.com/openid/AppAuth-Android/files/511863/codeAndlogs.zip)

**Comment by iainmcgin** [comment] 2016-10-05 20:50
Thanks for providing your code. From looking at it, I can't see anything wrong with the overall approach. Some questions to help me diagnose:

- What version of the library are you dependent on?
- After wiping application data and running the application, do you at least see a custom tab / browser instance appear for the authorization flow before the application closes? 
- If you install the AppAuth demo app on your demo device, for the same version your app is dependent on, can you reproduce the problem there too?
- The log you provided doesn't include any of the AppAuth log statements. You may need to enable verbose logging for the AppAuth tag (`adb shell setprop log.tag.AppAuth VERBOSE`) so we can see this. Specifically, I'd be interested to know what browser is being targeted for running the auth flow? This should be logged as "Using PACKAGE_NAME as browser for auth". Knowing whether this changes (though this seems unlikely) between first and second run would also be useful.

If you are able, stepping through the code of `performAuthorizationRequest` to see at what point your app dies would be useful. At this point I suspect something is going wrong in dispatching the intent to the browser for the authorization flow, and because you call finish() immediately after performAuthorizationRequest this is resulting in an empty task ("dead" app, removed from app switcher).

**Comment by Mayranit** [comment] 2016-10-05 21:15
Hi, Below are the answers .

1. I have tried this in both versions of AppAuth (0.2.0 & 0.3.0)

2.  Yes , I see custom tab instance appear for authorization flow before application closes

3. I have not tried that. But I have a sample app and real production app. Both has this issue.

4. I have attached the Library log. It has both success and failure logs. My device has Chrome browser. And it uses it.

5. It goes through all the lines and application get closed after "this.mContext.startActivity(intent);"  I tried removing the Finish() from my code, but still app closes. (I did that just to check what is happening in the lib)

[Logs.zip](https://github.com/openid/AppAuth-Android/files/512343/Logs.zip)

**Comment by iainmcgin** [comment] 2016-10-05 23:30
OK, so we know at least the browser is being correctly triggered. Is the custom tab closing immediately upon opening, or do you interact with it first before it closes? The OAuth flags you were setting in the code you provided indicated that the user should at least have to tap on something before the flow closes, but I'd like to confirm that with you.

If the auth flow is working as expected, this leaves the delivery of the response as the potential issue. If you place a breakpoint in RedirectUriReceiverActivity.onCreate, do you see this code executing on first run? Based on the failure log you provided, I suspect this activity is not being triggered, as I would expect to see the log lines related to retrieving the original request and target intents, which we do see in the success case:

```
V/AppAuth: Retrieving original request for state ...
V/AppAuth: Retrieving pending intent for scheme ...
```

I have tried to replicate your problem using the AppAuth demo app built from 0.3.0, but was not able to. You can download the version I built for testing here, and see what happens for you:

www.iainmcgin.co.uk/appauth/github-112/appauth-demoapp-0.3.0.apk

When running this, I see the RedirectUriReceiverActivity clearly invoked at the completion of the flow in my logs (from ActivityManager tag)

```
START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=com.googleu
                               sercontent.apps.AAA:/oauth2redirect?state=BBB&code=CCC&authuser=0&session_state=DDD&prompt=consent flg=0x10000000 cmp=net.openid.appauthdemo/n
                               et.openid.appauth.RedirectUriReceiverActivity (has extras)} from uid 10035 on display 0
```

So, check to see if you see a similar log line (with your custom scheme) after completion of the flow. If you don't see it, something is failing in Chrome or your app's configuration that is preventing the hand-off from the browser back to RedirectUriReceiverActivity.

Can you provide the section of your AndroidManifest.xml that exposes the RedirectUriReceiverActivity on your custom scheme? Just in case you have any additional configuration there that could be causing a problem, though I don't understand how that would be affected by clearing data and restarting the application.

**Comment by Mayranit** [comment] 2016-10-06 15:15
Hi, Custom tab closes immediately after opening. No user interaction at that point of time. 

On failure case , the call is not reaching up to RedirectUriReceiverActivity onCreate().


XML File declaration
----------------------------

<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:scheme="modestomyaccount"/>
            </intent-filter>
        </activity>

-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by Mayranit** [comment] 2016-10-06 15:16
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data android:scheme="modestomyaccount"/>
            </intent-filter>
        </activity>

**Comment by iainmcgin** [comment] 2016-10-06 18:50
Is the browser closing immediately expected? For instance, depending on the behavior of the OAuth2 server implementation, if the user has already consented to the particulars of the authorization request the redirect may happen immediately. Though, this typically _shouldn't_ kill the browser tab, especially if the redirect is not being forwarded to the RedirectUriReceiverActivity.

I'm not sure what else to suggest, at this point. Did you attempt to reproduce the behavior with the demo app I built and linked? Would you be able to provide a build of your app for me to replicate the behavior on my end? You can send it directly to me rather than sharing here if that helps, to iainmcgin@google.com

**Comment by Mayranit** [comment] 2016-10-06 18:54
Hi , Your demo app not having the issue which I am facing in my apps. I will check with my team and email you the build of our App. Thanks for the update.

**Comment by iainmcgin** [comment] 2016-10-06 18:58
My guess is that this may be some issue with Chrome Custom tabs, or your OAuth2 provider. I don't know why clearing data influences this at all.

**Comment by Mayranit** [comment] 2016-11-03 14:05
Issue is in Chrome custom tab, after Chrome update , I am not seeing this issue in the app now. Thanks for your updates.

**Closed** 2016-11-08 19:21 UTC
Labels: question
