### ISSUE TITLE
Is possible add new account with no phone configuration?

### ISSUE THREAD

**Issue by Kyba1985** [openid/AppAuth-Android#198] opened 2017-03-20 16:52 UTC
Hi,
i'm migrating from webview oauth2 android to appauth. 
I have noticed that if i want add a new account in the sample app, i need configure the new account on the phone; in the webview i could configure a new account and get the token in "light mode", without to be forced configure the new account on the phone.
Is it possible with this library create a new account like the webview?

Thanks in advance.

**Comment by iainmcgin** [comment] 2017-03-20 17:00
Duplicate of #194 / #173 / #172 - this is an issue with Chrome that I am working with the Chrome team to resolve. I'll close this issue, please follow the others for updates.

**Closed by iainmcgin** 2017-03-20 17:00 UTC
