### ISSUE TITLE
Redirect URI Problems

### ISSUE THREAD

**Issue by mattfred** [openid/AppAuth-Android#491] opened 2019-08-28 21:41 UTC
I have a custom redirect URI `customuri://com.baseurl/auth`. I have this value set in the manifest as shown here:

        <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="customuri://com.baseurl/auth"/>
            </intent-filter>
        </activity>

When watching the web traffic after logging in I see a redirect call being made with this url `https://my.baseurl.com/connect/authorize?redirect_uri=customuri://com.baseurl/auth`

The redirect does not work. The app is never called again, the chrome browser just shows an empty webpage. What am I doing wrong?

**Comment by andresubri** [comment] 2019-08-29 21:27
You can test this in Chrome, if it doesn't work then the problem is on your side, make sure it is actually redirecting to your app.

**Comment by vinhphucit** [comment] 2020-01-06 07:50
It seems like this error happens on Android 9 and 10 only, does anyone find solution?

**Comment by dsuresh-ap** [comment] 2020-03-19 19:00
Shouldn't it be like this:
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="customuri"
                       android:host="com.baseurl" />
        </intent-filter>
    </activity>
```

Where `scheme` is `customuri` and the `host` is `com.baseurl`? There is more info [here for the data tag](https://developer.android.com/guide/topics/manifest/data-element).

**Comment by Tgo1014** [comment] 2021-01-18 12:51
That was my issue @dsuresh-ap. Thanks!

**Comment by agologan** [comment] 2021-06-03 15:26
@dsuresh-ap is right. The data element in the OP's question was incorrectly defined.
Closing the issue.

**Closed by agologan** 2021-06-03 15:26 UTC
