### ISSUE TITLE
Issues with intent on Firefox only.

### ISSUE THREAD

**Issue by maartenaalbers** [openid/AppAuth-Android#494] opened 2019-09-10 09:13 UTC
Hi,
We are using the SDK for a while, but apparently it goes wrong if you select Firefox in the BrowserSelector.
We do end up in the `AuthorizationManagementActivity` like it is when using Chrome.
But when it tries to extract the state in the onCreate (`extractState(getIntent().getExtras());`) it finishes the activity because `state == null`.
Tried to install a number of different browsers, but only Firefox is failing.

**Comment by tobi512** [comment] 2019-11-19 08:30
Hi @maartenaalbers, 
we have the same issue without explicitly selecting Firefox in some (seldom) cases, so it seems like Firefox itself might not be the problem. Especially reproducible if you select "do not keep activities" in the Android developer settings on a device.

**Comment by agologan** [comment] 2021-06-07 21:31
I will assume this an outdated issue as I cannot reproduce it with Firefox or Firefox Focus.
@tobi512 same goes for "do not keep activities".

Closing this for now. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍

**Closed by agologan** 2021-06-07 21:31 UTC
