### ISSUE TITLE
TokenResponseCallback

### ISSUE THREAD

**Issue by mahendradabiaplite** [openid/AppAuth-Android#839] opened 2022-06-08 07:40 UTC
AuthorizationException with error code 9 and null error field. anyone can help me what does mean by code 9 ?

**Comment by CompileConnected** [comment] 2022-10-25 06:55
This is not a bug.

it's  Indicates that a received ID token is invalid

for further more information please google it,
if you stumble any more code, please check in here
https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationException.java

find your code and google it

**Comment by agologan** [comment] 2022-10-27 18:22
Marking as resolve per @CompileConnected 's answer.
Thanks for the assist.

**Closed by agologan** 2022-10-27 18:22 UTC
Labels: help wanted
