### ISSUE TITLE
Customize the browser to hide url

### ISSUE THREAD

**Issue by shraddha1112** [openid/AppAuth-Android#277] opened 2017-10-08 08:59 UTC
Hello,
Is it possible to customize the browser page that opens to hide the url?

Also want to automatically close the browser once use had authenticated and clicked on allow button.
Please respond.

Regards,
Shraddha

**Comment by iainmcgin** [comment] 2017-10-08 18:57
There is no way to hide the URL on a custom tab or system browser, by design: this ensures that the user understands the context in which they are being asked to enter credentials and give consent. As for automatically closing the browser, this will already happen if you are using a custom tab and the redirect is handled by your app. If you're using a system browser, the app will regain focus but the browser will stay on whatever page it was left on if you switch back to it; there's no way to change that.

**Comment by shraddha1112** [comment] 2017-10-09 06:14
Thanks for your comment.

**Comment by shraddha1112** [comment] 2017-10-09 07:33
But we want to hide the browser URL. 
If there is any other alternative please help.

**Comment by panva** [comment] 2017-10-09 08:24
There is no way to hide the URL on a custom tab or the system browser, just like there isn't a way for you to do this in your standard desktop browser. This is by design.

I strongly recommend [#section-8.12 on Embedded User-Agents](https://tools.ietf.org/html/rfc8252#section-8.12) of the Best Current Practice for OAuth 2.0 Native Apps to understand why AppAuth does not allow the use of embedded user-agents which would allow you to hide the bar, but would come with very significant drawbacks.

Google is also actively blocking the use of known embedded user-agents, meaning you can't use them without violating the terms of use of the service.

**Closed** 2017-10-09 15:15 UTC

**Comment by kishansolankiOpenxcell** [comment] 2020-11-06 13:02
It's now 2020. Are we able to hide the URL now?
